CREATE TABLE userprofiles (
    id INTEGER NOT NULL PRIMARY KEY,
    address1 TEXT,
    address2 TEXT,
    city TEXT,
    stateregion TEXT,
    country TEXT,
    phone TEXT,
    cellphone TEXT,
    sms INTEGER,
    email TEXT,
    maritalstatus TEXT,
    university1 TEXT,
    university2 TEXT,
    linkedinurl TEXT,
    instagramurl TEXT,
    vimeourl TEXT,
    facebookurl TEXT,
    googleurl TEXT,
    university TEXT,
    title TEXT,
    pronoun TEXT,
    title2 TEXT,
    activepictureurl TEXT,
    userid INTEGER,
    employeeid TEXT,
    postalzip TEXT,
    companyid TEXT,
    buid INTEGER,
    managerid INTEGER,
    regionid INTEGER,
    branchid INTEGER,
    fullname TEXT,
    firstname TEXT,
    lastname TEXT,
    defaultinstanceid TEXT,
    defaultshardid TEXT
);
